#include "clock_custom.h"
#include "stm32f4xx_hal.h"
void clock_custom(void){
  RCC_OscInitTypeDef o={0}; RCC_ClkInitTypeDef c={0};
  __HAL_RCC_PWR_CLK_ENABLE(); __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE2);
  o.OscillatorType=RCC_OSCILLATORTYPE_HSE; o.HSEState=RCC_HSE_ON;
  o.PLL.PLLState=RCC_PLL_ON; o.PLL.PLLSource=RCC_PLLSOURCE_HSE; o.PLL.PLLM=5; o.PLL.PLLN=192; o.PLL.PLLP=RCC_PLLP_DIV4; o.PLL.PLLQ=4;
  HAL_RCC_OscConfig(&o);
  c.ClockType=RCC_CLOCKTYPE_SYSCLK|RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  c.SYSCLKSource=RCC_SYSCLKSOURCE_PLLCLK; c.AHBCLKDivider=RCC_SYSCLK_DIV1; c.APB1CLKDivider=RCC_HCLK_DIV2; c.APB2CLKDivider=RCC_HCLK_DIV1;
  HAL_RCC_ClockConfig(&c, FLASH_LATENCY_3);
  __HAL_RCC_GPIOA_CLK_ENABLE(); GPIO_InitTypeDef g={0}; g.Pin=GPIO_PIN_8; g.Mode=GPIO_MODE_AF_PP; g.Pull=GPIO_NOPULL; g.Speed=GPIO_SPEED_FREQ_VERY_HIGH; g.Alternate=GPIO_AF0_MCO;
  HAL_GPIO_Init(GPIOA,&g); HAL_RCC_MCOConfig(RCC_MCO1,RCC_MCO1SOURCE_HSE,RCC_MCODIV_1);
}
